apply plugin: 'com.android.application'

// 加载密钥库配置
def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion compileApi

    defaultConfig {
        targetSdkVersion targetApi
        minSdkVersion project.getProperties().get("SDK_VERSION")
        multiDexEnabled true
    }

    // 添加签名配置
    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
            // 使用签名配置
            signingConfig signingConfigs.release
        }
    }

    packagingOptions {
        exclude 'META-INF/versions/9/OSGI-INF/MANIFEST.MF'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        disable "Instantiatable"
    }
    namespace 'com.iiordanov.aRDP'
}

dependencies {
    api 'com.android.support:multidex:1.0.3'
    implementation project(':bVNC')
    implementation project(':pubkeyGenerator')
}
